# -*- coding: utf-8 -*-
"""siti rohmaniyah

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1G5NZYS3KUWMYJyXwAY05ZtIIjeGctAc_
"""

import cv2
import sys
imagepath = sys.argv [1]
cascpath = "haarcasecade_pedestrian.xml"
# cascpath = "pedestrian_another.xml"
# cascpath = "haarcasecade_fullbody.xml"

pedsCascade = cv2.cascadeClassifier(cascPath)
# read the image
image = cv2.imread(imagepath)
gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
# detect pedestrian in pic
peds = pedsCascade.detectMultiScale(
    gray,
    scaleFactor=1.3,
    minNeighbors=9,
    minSize=(30, 30)
)

print("Found {0} pedestrian!".format(len(peds)))
# Draw a rectangle around the peds
   cv2.rectangle(image, (x, y), (x+w, y+h), (0, 255, 0), 2)

# cv2.imshow("Faces found", image)
status = cv2.imwrite('peds_saved.jpg', image)
print (image written to file-system : ",status)

